config/routes.rb
Rails.application.routes.draw do
  # resources :users
  devise_for :users
  resources :users do
    member do
      patch :change_password
      get 'add_to_employee'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  resources :employees
  resources :departments 
  resources :bills do
    member do
      patch :approve
      patch :reject
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  belongs_to :department
  has_many :bills
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :designation, presence: true
  validates :department_id, presence: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  # before_action :authorize_admin!
  before_action :authorize_employee, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    if params[:user_id]
      user = User.find(params[:user_id])
      @employee = Employee.new(user_id: user.id, email: user.email)
    else
      @employee = Employee.new
    end
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.user = current_user

    if @employee.save
      redirect_to employees_path, notice: 'Employee was successfully created.'
    else
      redirect_to users_path, alert: @employee.errors.full_messages.join(', ')
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path, notice: 'Employee was successfully deleted.'
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :designation, :department_id)
  end

  def authorize_admin!
    redirect_to root_path, alert: 'Access denied!' unless current_user.admin?
  end

  def authorize_employee
    authorize Employee
  end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: @employee, local: true) do |form| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="row">
      <div class="column">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "u-full-width" %>
      </div>
      <div class="column">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "u-full-width" %>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <%= form.label :email %>
        <%= form.email_field :email, class: "u-full-width" %>
      </div>
      <div class="column">
        <%= form.label :designation %>
        <%= form.text_field :designation, class: "u-full-width" %>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <%= form.label :department_id %>
        <%= form.collection_select :department_id, Department.all, :id, :name, {}, { class: "u-full-width" } %>
      </div>
    </div>

    <div class="row">
      <div class="column">
        <%= form.submit @employee.new_record? ? "Create Employee" : "Update Employee", class: "button-primary" %>
        <%= link_to 'Cancel', @employee, class: "button button-outline" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/edit.html.erb
<div class="container">
  <h1>Edit Employee</h1>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="column column-50">
    <h1>Employees</h1>
  </div>
  <div class="column column-50 text-right">
    <%= link_to 'New Employee', new_employee_path, class: 'button button-outline' %>
  </div>
</div>

<table class="table-with-borders">
  <thead>
    <tr>
      <th> ID </th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Designation</th>
      <th>Department</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.id %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.department.name %></td>
        <td>
          <%= link_to 'Show', employee_path(employee) %>
          <%= link_to 'Edit', edit_employee_path(employee) %>
          <%= link_to 'Destroy', employee_path(employee),data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<div class="container">
  <h1>New Employee</h1>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="container">
  <h1>Employee Details</h1>

  <div class="row">
    <div class="column column-50">
      <table class="table-with-borders">
        <tr>
          <th>First Name:</th>
          <td><%= @employee.first_name %></td>
        </tr>
        <tr>
          <th>Last Name:</th>
          <td><%= @employee.last_name %></td>
        </tr>
        <tr>
          <th>Email:</th>
          <td><%= @employee.email %></td>
        </tr>
        <tr>
          <th>Designation:</th>
          <td><%= @employee.designation %></td>
        </tr>
        <tr>
          <th>Department:</th>
          <td><%= @employee.department.name %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <%= link_to 'Edit', edit_employee_path(@employee), class: 'button button-outline' %>
      <%= link_to 'Back', employees_path, class: 'button button-clear' %>
    </div>
  </div>
</div>