config/routes.rb
Rails.application.routes.draw do
  # resources :users
  devise_for :users
  resources :users do
    member do
      patch :change_password
      get 'add_to_employee'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  resources :employees
  resources :departments 
  resources :bills do
    member do
      patch :approve
      patch :reject
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :trackable
  has_many :employees
  has_many :bills, foreign_key: :submitted_by

  def admin?
    role == 'admin'
  end

  def employee?
    role == 'employee'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change_password]
  before_action :authorize_admin, only: [:edit, :update, :destroy]
  def index
    @users = User.order(:id)
  end
  
  def edit
  end


  def show
    @user =  User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def change_password
    if @user.update(password_params)
      redirect_to @user, notice: 'Password was successfully updated.'
    else
      render :edit
    end
  end

  def add_to_employee 
    @user = User.find(params[:id])
    @employee = Employee.new(user_id: @user.id, email: @user.email) 
    redirect_to new_employee_path(user_id: @user.id) 
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end


  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def authorize_admin
    redirect_to(root_path, alert: 'You are not authorized to perform this action.') unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>


  <div class="field">
  <%= f.label :role %><br>
  <%= f.select :role, options_for_select(['admin', 'dummyuser', 'employee'], @user.role), prompt: 'Select a role' %>
  </div>


  <div class="actions">
    <%= f.submit 'Update User' %>
  </div>
<% end %>

<h2>Change Password</h2>

<%= form_for(@user, url: change_password_user_path(@user), method: :patch) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Change Password' %>
  </div>

<% end %>


<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<table class="table-with-borders">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Actions</th>
      <th>Make Employee</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to 'Show', user %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Destroy', user, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </td>
        <td>
          <% if user.present? %>
          <%= link_to 'Add to Employee', add_to_employee_user_path(user), class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>  
</table>  

app/views/users/show.html.erb
<h1 class="text-center">User Details</h1>
<div class="container">
  <div class="row">
    <div class="column column-50 column-offset-25">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center">User Information</h5>
          <p class="card-text">
            <strong>ID:</strong> <%= @user.id %><br>
            <strong>NAME:</strong> <%= @user.name %><br>
            <strong>Email:</strong> <%= @user.email %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>