config/routes.rb
Rails.application.routes.draw do
  # resources :users
  devise_for :users
  resources :users do
    member do
      patch :change_password
      get 'add_to_employee'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  resources :employees
  resources :departments 
  resources :bills do
    member do
      patch :approve
      patch :reject
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReimbursementPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <% if controller.controller_name == 'home' %>
      <%= stylesheet_link_tag "home", "data-turbo-track": "reload" %>
    <% end %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.min.css">
    
  </head>

<body>


  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  

 <header class="site-header">
    <div class="container">
      <nav class="site-nav">
        <div class="hamburger">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <a href="/" class="logo">ReimbursementPortal</a>
        <div class="nav-links">
          <% if user_signed_in? %>
            <% if policy(Employee).index? %>
              <%= link_to 'Employees', employees_path, class: 'nav-link' %>
            <% end %>
            <% if policy(Department).index? %>
              <%= link_to 'Departments', departments_path, class: 'nav-link' %>
            <% end %>
            <% if policy(Bill).index? %>
              <%= link_to 'Bills', bills_path, class: 'nav-link' %>
            <% end %>
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to sign-out?" }, class: 'button' %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'button' %>
          <% end %>
        </div>
      </nav>
    </div>
  </header>

  <main class="site-main">
    <div class="container">
      <%= yield %>
    </div>
  </main>

  <footer class="site-footer bg-dark text-white animate-fade-in">
    <div class="container d-flex justify-content-between">
      <p>&copy; <%= Time.current.year %> ReimbursementPortal. All rights reserved.</p>

      <% if user_signed_in? %>
        <p>Logged in as: <%= current_user.email %> || role: <%= current_user.role %></p>
      <% end %>
    </div>
  </footer>
</body>
</html>